### ISSUE TITLE
There is no option to customize the search engines and the addons search on only 6 search engines.

### ISSUE THREAD

**Issue by panderlad** [dessant/view-page-archive#13]
You write on Mozilla addons: "The enabled search engines and their order can be customized from the extension's options."

Supported search engines, archive and cache sources:

    Wayback Machine
    Google Cache
    Bing Cache
    Yandex Cache
    Archive.is
    Memento Time Travel
    WebCite
    Exalead Cache
    Gigablast Cache
    Sogou Snapshot
    Qihoo 360 Search Snapshot
    Baidu Snapshot
    Naver Cache
    Yahoo Japan Cache
    Megalodon

//

There is no option to customize the search engines and the addons search on only 6 search engines.

**Comment by dessant** [comment]
You have to enable additional search engines from the extension's options. In recent Firefox versions the options were made harder to find, there is a menu for each extension, three dots, the options can be accessed from that menu.

**Comment by dessant** [comment]
I do plan to add a settings button in some of my extension because of this change in Firefox, but it would best to also open a bug report for Firefox. Please tell them how hard it is to find extension options, or even discover that they exist. Previously there were large buttons that opened options for every extension in about:addons.

**Comment by dessant** [comment]
This is where you can file new Firefox bug reports: https://bugzilla.mozilla.org/home
