### ISSUE TITLE
repetitive license comments create a huge file

### ISSUE THREAD

**Issue by FredThompsonII** [dessant/view-page-archive#6]
commons.bundle.js in the Firefox extension has 14 copies of the Apache license and only 1 line of actual code.

Removing the duplicate license statements and unused code would reduce this file from 152K to 7.2K.

Why do you have all the unused stuff?

**Comment by FredThompsonII** [comment]
Similarly, the files in the contribute folder don't seem to be used because the contribute link goes directly to a paypal url. avocado-toast is 58K. Remove that folder as well and the xpi should be about 100K smaller, a reduction of 40%.

**Comment by dessant** [comment]
Each license notice belongs to a different package. I think it's not legal to strip licensing from code before redistribution. If you have a solution for moving out these notices from the file in a way that respects copyright law, I'd be happy to add it to the build script.

**Comment by dessant** [comment]
The contribution folder is a part of the extension, and the link does not go directly to PayPal.

**Comment by massonpj** [comment]
Are they actually, "duplicates"? Each original author, i.e. the copyright holder, for each package, library, file, etc. will include their own specific copyright information, (e.g. "Copyright 2019 Patrick Masson), so while the text of the Apache license may be the same, the attribution included in each licence will be unique. Thus in order to protect the copyright of the original author the license should be included.

From Apache (https://apache.org/dev/apply-license.html)

> APPENDIX: How to apply the Apache License to your work.
>
> To apply the Apache License to your work, attach the following
> boilerplate notice, with the fields enclosed by brackets "[]"
> replaced with your own identifying information. (Don't include
> the brackets!)  The text should be enclosed in the appropriate
> comment syntax for the file format. We also recommend that a
> file or class name and description of purpose be included on the
> same "printed page" as the copyright notice for easier
> identification within third-party archives.
> 
> Copyright [yyyy] [name of copyright owner]
